language: python
python:
  - "3.5"
services:
  - postgresql
before_script:
  - psql -c 'create database progressbot;' -U postgres

install: "pip install -r requirements.txt"
script: python test_server.py
